Repository delvedor/find-my-way, pull requests merged in 2022-05, with the labels that each got.

#273 Refactored handler storage
  handler_storage.js
  index.js
  lib/pretty-print.js
Labels: enhancement

#283 Optimized creating result params object
  handler_storage.js
  index.js
Labels: enhancement

#281 Fix issue #280
  index.js
  test/issue-280.test.js
Labels: bugfix

#282 Fix parameters decoding
  index.js
  lib/url-sanitizer.js
  package.json
  test/custom-decode-uri.test.js
  test/issue-234.test.js
Labels: bugfix

#278 Change lookup result type to any
  index.d.ts
  test/types/router.test-d.ts
Labels: typescript

#284 Add querrystring parser
  README.md
  index.d.ts
  index.js
  lib/url-sanitizer.js
  test/custom-querystring-parser.test.js
  test/methods.test.js
  test/querystring.test.js
  test/store.test.js
Labels: feature

#275 Fixed must match constraints check
  handler_storage.js
  lib/constrainer.js
  lib/pretty-print.js
  test/constraint.default-versioning.test.js
  test/constraints.test.js
  test/issue-254.test.js
Labels: bugfix

#279 Add addConstraintStrategies method
  README.md
  index.d.ts
  index.js
  lib/constrainer.js
  test/constraint.custom-versioning.test.js
  test/constraint.custom.test.js
  test/constraints.test.js
  test/types/router.test-d.ts
Labels: enhancement

#270 Adding feature ignoreDuplicateSlashes with tests
  README.md
  index.d.ts
  index.js
  test/errors.test.js
  test/issue-240.test.js
  test/methods.test.js
  test/optional-params.test.js
  test/path-params-match.test.js
  test/server.test.js
  test/types/router.test-d.ts
Labels: feature
